// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vezcguasbqadkrodaxen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlemNndWFzYnFhZGtyb2RheGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjMwMTYsImV4cCI6MjA2MTAzOTAxNn0.H8TV-IT0xl5iiyr66ogpRvHTrkZ8qWDhmY_ImKClG28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);